changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - dependabot
      - pre-commit-ci[bot]
  categories:
    - title: Bug Fixes
      labels:
        - bug
    - title: Enhancements
      labels:
        - enhancement
    - title: Maintenance
      labels:
        - maintenance
    - title: Other Changes
      labels:
        - "*"